### ISSUE TITLE
De `runSelectQuery` en de `readManyRows` lijken erg op elkaar, dit is niet D.R.Y.

### ISSUE THREAD

**Issue by JeroenHeemskerk** [PatrickLubbers/educom-webshop-oop-1706014168#17]
Onderstaande functies 
https://github.com/PatrickLubbers/educom-webshop-oop-1706014168/blob/6f4691bc77d255c68a4ec51feabd91015e0d258a/models/Crud.php#L28-L37
https://github.com/PatrickLubbers/educom-webshop-oop-1706014168/blob/6f4691bc77d255c68a4ec51feabd91015e0d258a/models/Crud.php#L72-L84
lijken erg op elkaar, 

Dit is niet [D.R.Y. Don't Repeat Yourself](https://e-learning.educom.nu/essentials/ProgrammingBasics/coding-standards#dry---dont-repeat-yourself)

Kan je in de CrudShop niet de `readManyRows` gebruiken?

**Comment by PatrickLubbers** [comment]
Ga ik doen ja, scheelt ook weer code!
