### ISSUE TITLE
Gebruik geen echo's in de SessionMananger

### ISSUE THREAD

**Issue by JeroenHeemskerk** [PatrickLubbers/educom-webshop-oop-1706014168#18]
https://github.com/PatrickLubbers/educom-webshop-oop-1706014168/blob/6f4691bc77d255c68a4ec51feabd91015e0d258a/models/SessionManager.php#L37-L44

**Comment by PatrickLubbers** [comment]
Ik dacht er eerst aan op een andere manier een bericht te tonen als de cart bv al leeg is en deze in een variabele $message te returnen, lijkt me beter helemaal geen bericht mee te sturen.
